export const USER_SUBSCRIBE = 'USER_SUBSCRIBE';
export const USER_FACEBOOK_LOGIN = 'USER_FACEBOOK_LOGIN';
export const USER_SUBSCRIBE_NEWSLETTER = 'USER_SUBSCRIBE_NEWSLETTER';

export const ACTION_ADD_USER_COLLECTION = 'ACTION_ADD_USER_COLLECTION';
export const ACTION_SHOW_RANDOM_ADVICE = 'ACTION_SHOW_RANDOM_ADVICE';

export const COUNT_INSIGHTS_COLLECTIONS = 'COUNT_INSIGHTS_COLLECTIONS';
export const COUNT_INSIGHTS_PLUS = 'COUNT_INSIGHTS_PLUS';
export const SET_COLLECTIONS = 'SET_COLLECTIONS';
export const SET_CURRENT_COLLECTION = 'SET_CURRENT_COLLECTION';
export const SET_INSIGHTS_USELESS = 'SET_INSIGHTS_USELESS';
export const SET_INSIGHTS_USEFUL = 'SET_INSIGHTS_USEFUL';
export const UPDATE_COLLECTIONS = 'UPDATE_COLLECTIONS';
export const MOVEMENT_INSIGHTS_IN_COLLECTION = 'MOVEMENT_INSIGHTS_IN_COLLECTION';
export const UPDATE_ADVICES_COLLECTIONS = 'UPDATE_ADVICES_COLLECTIONS';


export const TOPICS_FORCE_FETCH = 'TOPICS_FORCE_FETCH';
export const SAVE_UNIQUE_ID_AND_DATE = 'SAVE_UNIQUE_ID_AND_DATE';
export const USER_TURN_NOTIFICATIONS = 'USER_TURN_NOTIFICATIONS';


export const UPDATE_APP_START_TIME = '@AsyncStorage:UPDATE_APP_START_TIME';
export const APP_BACKGROUND_TIME = '@AsyncStorage:APP_BACKGROUND_TIME';
export const STORAGE_KEY = '@AsyncStorage:notification';


export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';


export function setUsefulAction (data) {
  return {
    type: SET_INSIGHTS_USEFUL,
    data
  };
};

export function setUselessAction (data) {
  return {
    type: SET_INSIGHTS_USELESS,
    data
  };
};
